xtest: pkcs11: fix compile error with init_lib_and_find_token_slot()
Commit b38e9e06fcbd ("xtest: pkcs11: add PKCS11 ACL auth test") added a
new parameter to init_lib_and_find_token_slot() but omitted to update
one call site. Fix that.

Fixes the following compile error:

 pkcs11_1000.c: In function ‘xtest_pkcs11_test_1026’:
 pkcs11_1000.c:8533:7: error: too few arguments to function ‘init_lib_and_find_token_slot’
  8533 |  rv = init_lib_and_find_token_slot(&slot);
       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>