pkcs11: fix regression in RSA AES key wrap tests
Fixes the warning:
 29659:  pkcs11_1000.c: In function ‘test_rsa_aes_wrap’:
 29660:  pkcs11_1000.c:8249:51: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘size_t’ {aka ‘unsigned int’} [-Werror=format=]
 29661:   8249 |    "Test RSA AES wrap/unwrap of %lu %s key with %lu RSA",
 29662:        |                                                 ~~^
 29663:        |                                                   |
 29664:        |                                                   long unsigned int
 29665:        |                                                 %u
 29666:   8250 |    target_bits, (t->target_type == CKK_AES) ? "AES" : "RSA",
 29667:   8251 |    t->key.modulus_len * 8);
 29668:        |    ~~~~~~~~~~~~~~~~~~~~~~
 29669:        |                       |
 29670:        |                       size_t {aka unsigned int}

Fixes: 942159ad8611 ("xtest: pkcs11: Add test for RSA AES key wrap mechanism")
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>