regression 6000: fix uninitialized local variables
Reported by GCC 8.2.0 with traces like:

.../build/optee_test/host/xtest/regression_6000.c:495:8: error: ‘count’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  (void)ADBG_EXPECT_BUFFER(c, &data_00[5], 5, out, count);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../build/optee_test/host/xtest/regression_6000.c:465:11: note: ‘count’ was declared here
  uint32_t count;
           ^~~~~
.../build/optee_test/host/xtest/regression_6000.c:192:23: error: ‘obj’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  op.params[0].value.a = obj;
  ~~~~~~~~~~~~~~~~~~~~~^~~~~
.../build/optee_test/host/xtest/regression_6000.c:463:11: note: ‘obj’ was declared here
  uint32_t obj;
           ^~~

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>