xtest: pkcs11: fix unused errors
Fix unused parameter and unused variable errors with building
pkcs11_1000.c with OPENSSL disabled, i.e. WITH_OPENSSL = n or undefined.

host/xtest/pkcs11_1000.c:7425:49: error: unused parameter 'c' [-Werror,
-Wunused-parameter]
static void xtest_pkcs11_test_1024(ADBG_Case_t *c)
                                                ^

host/xtest/pkcs11_1000.c:7409:19: error: unused variable
'x509_example_root_ca' [-Werror,-Wunused-const-variable]
static const char x509_example_root_ca[] =
                  ^

Signed-off-by: Victor Chong <victor.chong@linaro.org>
Reviewed-by: Jerome Forissier <jerome@forissier.org>